config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  root 'customers#index'
  resources :users
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :email,
             :presence =>true,
             :uniqueness => true,
             :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
             :message => "This field is required." }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable ,
         :omniauthable, :omniauth_providers => [:facebook]
  validates :email,
             :presence =>true,
             :uniqueness => true,
             :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
             :message => "This field is required." }
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
      if ["facebook"].include?(auth.provider)
        user.save(:validate => false)
      else
        user.email = auth.info.email
        user.save
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :authenticate_user!
	before_action :find_customer, :only => [:show, :edit , :update, :destroy]

  def index
  	@customers = Customer.all
  end

  def new
    @customer = Customer.new
  end
 
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'customer was successfully created.' }
        format.json { render json: show, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'customer was successfully updated.' }
        format.json { render json: show, status: :ok, location: @customer }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	@customer.destroy
  	redirect_to customers_path
  end

  private
  def find_customer
  	@customer = Customer.find(params[:id])
  end

  def customer_params
  	params.require(:customer).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.haml
= form_for @customer, html: { multipart: true }  do |f|
  = f.label 'Email'
  = f.text_field :email 
  = f.label 'First Name'
  = f.text_field :first_name 
  = f.label 'Last Name'
  = f.text_field :last_name 
  = f.label 'Profile Picture' 
  = f.file_field :image
  = f.submit "Submit"

app/views/customers/edit.html.haml
%h1 Update User
= render 'form'

app/views/customers/index.html.haml
.container.bg-9
  .row
    %br/
    %h1 Listing Users
    %table.table.table-bordered.table-striped
      %thead
        %tr
          %th Email
          %th First Name
          %th Last Name
          %th Profile Picture
        - @customers.each do |customer|
          %tr
            %td= customer.email
            %td= customer.first_name
            %td= customer.last_name
            %td= customer.image.url(:medium)
            %td= link_to 'show', customer_path(customer)
            %td= link_to 'edit', edit_customer_path(customer)
            %td= link_to 'destroy', customer_path(customer), method: :delete, data: { clear:'Are you sure?'}
    = link_to "New User", new_customer_path, :class => "btn btn-success", :style => "text-decoration:none"

app/views/customers/new.html.haml
%h1 Create New User
= render 'form'

app/views/customers/show.html.haml
.container.bg-9
  .row
    %br/
    %p
      %strong Email:
      = @customer.first_name
    %p
      %strong First Name:
      = @customer.first_name
    %p
      %strong Last Name:
      = @customer.last_name
    %p
      %strong Profile Picture:
      = @customer.image.url(:medium)
    = link_to 'Back', customers_path, :class => "btn btn-success", :style => "text-decoration:none"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if user_signed_in? %>
    <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :style => "text-decoration:none" %></li>
   <% end %>
    <%= yield %>
  </body>
</html>